-- Festival Database V1
-- 현재 운영 중인 Supabase 구조를 재현하기 위한 마이그레이션 파일

-- =========================================================
-- 1. festivals 보완
-- =========================================================

alter table public.festivals
add column if not exists address text,
add column if not exists region text,
add column if not exists official_url text,
add column if not exists status text default 'scheduled',
add column if not exists thumbnail_url text,
add column if not exists price_type text,
add column if not exists slug text;

alter table public.festivals
alter column start_date set not null,
alter column end_date set not null;

alter table public.festivals
drop constraint if exists festivals_valid_date_range;

alter table public.festivals
add constraint festivals_valid_date_range
check (
  end_date >= start_date
);

alter table public.festivals
drop constraint if exists festivals_valid_category;

alter table public.festivals
add constraint festivals_valid_category
check (
  category is null
  or category in (
    'music_festival',
    'local_festival',
    'food_festival',
    'culture_festival',
    'other'
  )
);

alter table public.festivals
drop constraint if exists festivals_valid_verification_status;

alter table public.festivals
add constraint festivals_valid_verification_status
check (
  verification_status is null
  or verification_status in (
    'pending',
    'approved',
    'rejected'
  )
);

alter table public.festivals
drop constraint if exists festivals_valid_status;

alter table public.festivals
add constraint festivals_valid_status
check (
  status is null
  or status in (
    'scheduled',
    'ongoing',
    'ended',
    'cancelled'
  )
);

alter table public.festivals
drop constraint if exists festivals_valid_price_type;

alter table public.festivals
add constraint festivals_valid_price_type
check (
  price_type is null
  or price_type in (
    'free',
    'paid',
    'partial_free',
    'unknown'
  )
);

create unique index if not exists festivals_slug_unique
on public.festivals (slug)
where slug is not null;

create unique index if not exists festivals_name_start_location_unique
on public.festivals (
  lower(trim(name)),
  start_date,
  lower(trim(coalesce(location, '')))
);

create index if not exists idx_festivals_region
on public.festivals (region);

create index if not exists idx_festivals_status
on public.festivals (status);

create index if not exists idx_festivals_verification_status
on public.festivals (verification_status);

create index if not exists idx_festivals_date_range
on public.festivals (start_date, end_date);

-- =========================================================
-- 2. artists 보완
-- =========================================================

alter table public.artists
add column if not exists normalized_name text,
add column if not exists artist_type text,
add column if not exists image_url text;

alter table public.artists
drop constraint if exists artists_valid_artist_type;

alter table public.artists
add constraint artists_valid_artist_type
check (
  artist_type is null
  or artist_type in (
    'singer',
    'band',
    'dj',
    'group',
    'performance_team',
    'other'
  )
);

create unique index if not exists artists_normalized_name_unique
on public.artists (normalized_name)
where normalized_name is not null;

-- =========================================================
-- 3. festival_artists 보완
-- =========================================================

alter table public.festival_artists
add column if not exists performance_date date,
add column if not exists performance_time time,
add column if not exists stage_name text,
add column if not exists status text default 'confirmed',
add column if not exists source_url text,
add column if not exists created_at timestamptz default now();

alter table public.festival_artists
drop constraint if exists festival_artists_valid_status;

alter table public.festival_artists
add constraint festival_artists_valid_status
check (
  status is null
  or status in (
    'scheduled',
    'confirmed',
    'cancelled'
  )
);

-- =========================================================
-- 4. festival_candidates 생성
-- =========================================================

create table if not exists public.festival_candidates (
  id bigint generated by default as identity primary key,

  title text not null,
  source_url text not null,
  source_type text,

  raw_text text,

  festival_name text,
  start_date date,
  end_date date,
  location text,
  category text,

  score integer default 0,
  status text not null default 'pending',

  reject_reason text,
  reviewed_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),

  festival_id bigint,

  constraint festival_candidates_source_url_unique
    unique (source_url),

  constraint festival_candidates_valid_date_range
    check (
      start_date is null
      or end_date is null
      or end_date >= start_date
    ),

  constraint festival_candidates_valid_category
    check (
      category is null
      or category in (
        'music_festival',
        'local_festival',
        'food_festival',
        'culture_festival',
        'other'
      )
    ),

  constraint festival_candidates_valid_status
    check (
      status in (
        'pending',
        'approved',
        'rejected'
      )
    )
);

alter table public.festival_candidates
drop constraint if exists festival_candidates_festival_id_fkey;

alter table public.festival_candidates
add constraint festival_candidates_festival_id_fkey
foreign key (festival_id)
references public.festivals(id)
on delete set null;

create index if not exists idx_festival_candidates_status
on public.festival_candidates (status);

create index if not exists idx_festival_candidates_score
on public.festival_candidates (score);

create index if not exists idx_festival_candidates_created_at
on public.festival_candidates (created_at);

create index if not exists idx_festival_candidates_start_date
on public.festival_candidates (start_date);

-- =========================================================
-- 5. updated_at 자동 갱신
-- =========================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_festivals_updated_at
on public.festivals;

create trigger set_festivals_updated_at
before update on public.festivals
for each row
execute function public.set_updated_at();

drop trigger if exists set_festival_candidates_updated_at
on public.festival_candidates;

create trigger set_festival_candidates_updated_at
before update on public.festival_candidates
for each row
execute function public.set_updated_at();

-- =========================================================
-- 6. RLS
-- =========================================================

alter table public.festivals enable row level security;
alter table public.artists enable row level security;
alter table public.festival_artists enable row level security;
alter table public.festival_candidates enable row level security;
alter table public.pipeline_runs enable row level security;

drop policy if exists "Allow public read"
on public.festivals;

create policy "Allow public read"
on public.festivals
for select
to public
using (true);

drop policy if exists "Allow public read"
on public.artists;

create policy "Allow public read"
on public.artists
for select
to public
using (true);

drop policy if exists "Allow public read"
on public.festival_artists;

create policy "Allow public read"
on public.festival_artists
for select
to public
using (true);

drop policy if exists "Allow public read"
on public.pipeline_runs;

-- festival_candidates와 pipeline_runs는 공개 정책 없음
-- 따라서 anon 사용자는 접근 불가