-- Allow the same artist to have more than one performance in a festival.
alter table public.festival_artists
  add column if not exists id bigint generated by default as identity;

alter table public.festival_artists
  drop constraint if exists festival_artists_pkey;

alter table public.festival_artists
  add constraint festival_artists_pkey primary key (id);

create index if not exists festival_artists_festival_artist_idx
  on public.festival_artists (festival_id, artist_id);
