begin;

create table if not exists public.festival_update_logs (
  id bigint generated by default as identity primary key,
  festival_id bigint not null references public.festivals(id) on delete cascade,
  updated_by uuid not null default auth.uid(),
  source_type text,
  source_url text,
  source_file_name text,
  changes jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_festival_update_logs_festival_created
on public.festival_update_logs (festival_id, created_at desc);

alter table public.festival_update_logs enable row level security;

grant select, insert on public.festival_update_logs to authenticated;
grant usage, select on sequence public.festival_update_logs_id_seq to authenticated;

drop policy if exists "Admins can read festival update logs"
on public.festival_update_logs;
create policy "Admins can read festival update logs"
on public.festival_update_logs
for select to authenticated
using ((select public.is_admin()));

drop policy if exists "Admins can insert festival update logs"
on public.festival_update_logs;
create policy "Admins can insert festival update logs"
on public.festival_update_logs
for insert to authenticated
with check ((select public.is_admin()));

create or replace function public.apply_festival_json_update(
  p_festival_id bigint,
  p_basic_changes jsonb default '{}'::jsonb,
  p_artists jsonb default '[]'::jsonb,
  p_tickets jsonb default '[]'::jsonb,
  p_change_log jsonb default '[]'::jsonb,
  p_source_type text default null,
  p_source_url text default null,
  p_source_file_name text default null
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_festival public.festivals%rowtype;
  v_artist_result jsonb := '{}'::jsonb;
  v_ticket jsonb;
  v_ticket_id bigint;
  v_ticket_count integer := 0;
  v_log_id bigint;
begin
  if not public.is_admin() then
    raise exception '관리자 권한이 필요합니다.' using errcode = '42501';
  end if;

  if pg_catalog.jsonb_typeof(coalesce(p_basic_changes, '{}'::jsonb)) <> 'object'
     or pg_catalog.jsonb_typeof(coalesce(p_artists, '[]'::jsonb)) <> 'array'
     or pg_catalog.jsonb_typeof(coalesce(p_tickets, '[]'::jsonb)) <> 'array'
     or pg_catalog.jsonb_typeof(coalesce(p_change_log, '[]'::jsonb)) <> 'array' then
    raise exception '업데이트 값의 JSON 형식이 올바르지 않습니다.' using errcode = '22023';
  end if;

  select * into v_festival
  from public.festivals
  where id = p_festival_id
  for update;

  if not found then
    raise exception '업데이트할 축제를 찾을 수 없습니다.' using errcode = 'P0002';
  end if;

  if v_festival.verification_status is distinct from 'approved' then
    raise exception '승인된 정식 축제만 업데이트할 수 있습니다.' using errcode = '22023';
  end if;

  update public.festivals
  set
    name = case when p_basic_changes ? 'name'
      then nullif(pg_catalog.btrim(p_basic_changes->>'name'), '') else name end,
    search_aliases = case when p_basic_changes ? 'search_aliases'
      then nullif(pg_catalog.btrim(p_basic_changes->>'search_aliases'), '') else search_aliases end,
    location = case when p_basic_changes ? 'location'
      then nullif(pg_catalog.btrim(p_basic_changes->>'location'), '') else location end,
    address = case when p_basic_changes ? 'address'
      then nullif(pg_catalog.btrim(p_basic_changes->>'address'), '') else address end,
    region = case when p_basic_changes ? 'region'
      then nullif(pg_catalog.btrim(p_basic_changes->>'region'), '') else region end,
    category = case when p_basic_changes ? 'category'
      then nullif(pg_catalog.btrim(p_basic_changes->>'category'), '') else category end,
    description = case when p_basic_changes ? 'description'
      then nullif(pg_catalog.btrim(p_basic_changes->>'description'), '') else description end,
    price_info = case when p_basic_changes ? 'price_info'
      then nullif(pg_catalog.btrim(p_basic_changes->>'price_info'), '') else price_info end,
    program_info = case when p_basic_changes ? 'program_info'
      then nullif(pg_catalog.btrim(p_basic_changes->>'program_info'), '') else program_info end,
    source_url = case when p_basic_changes ? 'source_url'
      then nullif(pg_catalog.btrim(p_basic_changes->>'source_url'), '') else source_url end,
    official_url = case when p_basic_changes ? 'official_url'
      then nullif(pg_catalog.btrim(p_basic_changes->>'official_url'), '') else official_url end,
    thumbnail_url = case when p_basic_changes ? 'thumbnail_url'
      then nullif(pg_catalog.btrim(p_basic_changes->>'thumbnail_url'), '') else thumbnail_url end,
    price_type = case when p_basic_changes ? 'price_type'
      then nullif(pg_catalog.btrim(p_basic_changes->>'price_type'), '') else price_type end,
    status = case when p_basic_changes ? 'status'
      then nullif(pg_catalog.btrim(p_basic_changes->>'status'), '') else status end,
    updated_at = now()
  where id = p_festival_id;

  if pg_catalog.jsonb_array_length(coalesce(p_artists, '[]'::jsonb)) > 0 then
    v_artist_result := public.import_festival_lineup(p_festival_id, p_artists);
  end if;

  for v_ticket in
    select value from pg_catalog.jsonb_array_elements(coalesce(p_tickets, '[]'::jsonb))
  loop
    v_ticket_id := nullif(v_ticket->>'existing_ticket_id', '')::bigint;

    if v_ticket_id is not null then
      update public.festival_ticket_rounds
      set
        round_type = nullif(pg_catalog.btrim(v_ticket->>'round_type'), ''),
        round_name = coalesce(nullif(pg_catalog.btrim(v_ticket->>'round_name'), ''), round_name),
        open_at = nullif(v_ticket->>'open_at', '')::timestamptz,
        price_info = nullif(pg_catalog.btrim(v_ticket->>'price_info'), ''),
        ticket_url = nullif(pg_catalog.btrim(v_ticket->>'ticket_url'), ''),
        ticket_platform = nullif(pg_catalog.btrim(v_ticket->>'ticket_platform'), '')
      where id = v_ticket_id and festival_id = p_festival_id;

      if not found then
        raise exception '수정할 티켓 정보를 찾을 수 없습니다: %', v_ticket_id;
      end if;
    else
      insert into public.festival_ticket_rounds (
        festival_id,
        round_type,
        round_name,
        open_at,
        price_info,
        ticket_url,
        ticket_platform
      ) values (
        p_festival_id,
        nullif(pg_catalog.btrim(v_ticket->>'round_type'), ''),
        coalesce(nullif(pg_catalog.btrim(v_ticket->>'round_name'), ''), '일반 예매'),
        nullif(v_ticket->>'open_at', '')::timestamptz,
        nullif(pg_catalog.btrim(v_ticket->>'price_info'), ''),
        nullif(pg_catalog.btrim(v_ticket->>'ticket_url'), ''),
        nullif(pg_catalog.btrim(v_ticket->>'ticket_platform'), '')
      );
    end if;

    v_ticket_count := v_ticket_count + 1;
  end loop;

  insert into public.festival_update_logs (
    festival_id,
    updated_by,
    source_type,
    source_url,
    source_file_name,
    changes
  ) values (
    p_festival_id,
    auth.uid(),
    nullif(pg_catalog.btrim(p_source_type), ''),
    nullif(pg_catalog.btrim(p_source_url), ''),
    nullif(pg_catalog.btrim(p_source_file_name), ''),
    coalesce(p_change_log, '[]'::jsonb)
  ) returning id into v_log_id;

  return pg_catalog.jsonb_build_object(
    'festival_id', p_festival_id,
    'log_id', v_log_id,
    'ticket_count', v_ticket_count,
    'artist_result', v_artist_result
  );
end;
$$;

revoke all on function public.apply_festival_json_update(
  bigint, jsonb, jsonb, jsonb, jsonb, text, text, text
) from public;
grant execute on function public.apply_festival_json_update(
  bigint, jsonb, jsonb, jsonb, jsonb, text, text, text
) to authenticated;

comment on table public.festival_update_logs is
  '승인된 정식 축제에 JSON으로 반영한 변경 이력';

comment on function public.apply_festival_json_update(
  bigint, jsonb, jsonb, jsonb, jsonb, text, text, text
) is '선택한 기본정보·라인업·티켓 변경만 원자적으로 반영하고 로그를 남긴다.';

commit;
