begin;

-- 관리자 표시 이름은 로그 작성 시점의 스냅샷으로 보관한다.
alter table public.profiles
add column if not exists display_name text;

update public.profiles
set display_name = case
  when role = 'admin' then '관리자'
  else '사용자'
end
where display_name is null or pg_catalog.btrim(display_name) = '';

alter table public.profiles
alter column display_name set default '사용자',
alter column display_name set not null;

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  actor_name text not null,
  action_type text not null,
  festival_id bigint references public.festivals(id) on delete set null,
  festival_name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_changes (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.audit_events(id) on delete restrict,
  entity_type text not null,
  entity_id text,
  entity_label text not null,
  operation text not null check (operation in ('insert', 'update', 'delete')),
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz not null default now(),
  constraint audit_changes_required_snapshots check (
    (operation = 'insert' and before_data is null and after_data is not null)
    or (operation = 'update' and before_data is not null and after_data is not null)
    or (operation = 'delete' and before_data is not null and after_data is null)
  )
);

create index if not exists audit_events_festival_created_idx
on public.audit_events (festival_id, created_at desc);

create index if not exists audit_changes_event_idx
on public.audit_changes (event_id, id);

alter table public.audit_events enable row level security;
alter table public.audit_changes enable row level security;

revoke all on table public.audit_events from public, anon, authenticated;
revoke all on table public.audit_changes from public, anon, authenticated;
revoke all on sequence public.audit_events_id_seq from public, anon, authenticated;
revoke all on sequence public.audit_changes_id_seq from public, anon, authenticated;

grant select on table public.audit_events to authenticated;
grant select on table public.audit_changes to authenticated;

create policy "Admins can read audit events"
on public.audit_events for select to authenticated
using ((select public.is_admin()));

create policy "Admins can read audit changes"
on public.audit_changes for select to authenticated
using ((select public.is_admin()));

-- 아래 함수들은 원본 변경과 로그 기록을 한 트랜잭션에서 처리한다.
create or replace function public.create_festival_with_audit(p_festival jsonb)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor_id uuid := auth.uid();
  v_actor_name text;
  v_festival public.festivals%rowtype;
  v_event_id bigint;
begin
  if not public.is_admin() then
    raise exception '관리자 권한이 필요합니다.' using errcode = '42501';
  end if;

  select coalesce(nullif(pg_catalog.btrim(display_name), ''), '관리자')
  into v_actor_name
  from public.profiles
  where id = v_actor_id;

  if v_actor_name is null then
    raise exception '관리자 프로필의 표시 이름을 확인해 주세요.' using errcode = '22023';
  end if;

  insert into public.festivals (
    name, normalized_name, search_aliases, start_date, end_date,
    location, address, region, category, description, thumbnail_url,
    official_url, price_type, price_info, program_info, status,
    verification_status
  ) values (
    nullif(pg_catalog.btrim(p_festival->>'name'), ''),
    nullif(pg_catalog.btrim(p_festival->>'normalized_name'), ''),
    nullif(pg_catalog.btrim(p_festival->>'search_aliases'), ''),
    nullif(p_festival->>'start_date', '')::date,
    nullif(p_festival->>'end_date', '')::date,
    nullif(pg_catalog.btrim(p_festival->>'location'), ''),
    nullif(pg_catalog.btrim(p_festival->>'address'), ''),
    nullif(pg_catalog.btrim(p_festival->>'region'), ''),
    nullif(pg_catalog.btrim(p_festival->>'category'), ''),
    nullif(pg_catalog.btrim(p_festival->>'description'), ''),
    nullif(pg_catalog.btrim(p_festival->>'thumbnail_url'), ''),
    nullif(pg_catalog.btrim(p_festival->>'official_url'), ''),
    nullif(pg_catalog.btrim(p_festival->>'price_type'), ''),
    nullif(pg_catalog.btrim(p_festival->>'price_info'), ''),
    nullif(pg_catalog.btrim(p_festival->>'program_info'), ''),
    coalesce(nullif(pg_catalog.btrim(p_festival->>'status'), ''), 'scheduled'),
    coalesce(nullif(pg_catalog.btrim(p_festival->>'verification_status'), ''), 'pending')
  ) returning * into v_festival;

  insert into public.audit_events (
    actor_id, actor_name, action_type, festival_id, festival_name
  ) values (
    v_actor_id, v_actor_name, 'festival.created', v_festival.id, v_festival.name
  ) returning id into v_event_id;

  insert into public.audit_changes (
    event_id, entity_type, entity_id, entity_label, operation, before_data, after_data
  ) values (
    v_event_id, 'festival', v_festival.id::text, v_festival.name,
    'insert', null, pg_catalog.to_jsonb(v_festival)
  );

  return v_festival.id;
end;
$$;

create or replace function public.update_festival_basic_info_with_audit(
  p_festival_id bigint,
  p_festival jsonb
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor_id uuid := auth.uid();
  v_actor_name text;
  v_before public.festivals%rowtype;
  v_after public.festivals%rowtype;
  v_event_id bigint;
begin
  if not public.is_admin() then
    raise exception '관리자 권한이 필요합니다.' using errcode = '42501';
  end if;

  select coalesce(nullif(pg_catalog.btrim(display_name), ''), '관리자')
  into v_actor_name
  from public.profiles
  where id = v_actor_id;

  if v_actor_name is null then
    raise exception '관리자 프로필의 표시 이름을 확인해 주세요.' using errcode = '22023';
  end if;

  select * into v_before
  from public.festivals
  where id = p_festival_id
  for update;

  if not found then
    raise exception '수정할 축제를 찾을 수 없습니다.' using errcode = 'P0002';
  end if;

  update public.festivals
  set
    name = nullif(pg_catalog.btrim(p_festival->>'name'), ''),
    normalized_name = nullif(pg_catalog.btrim(p_festival->>'normalized_name'), ''),
    search_aliases = nullif(pg_catalog.btrim(p_festival->>'search_aliases'), ''),
    start_date = nullif(p_festival->>'start_date', '')::date,
    end_date = nullif(p_festival->>'end_date', '')::date,
    location = nullif(pg_catalog.btrim(p_festival->>'location'), ''),
    address = nullif(pg_catalog.btrim(p_festival->>'address'), ''),
    region = nullif(pg_catalog.btrim(p_festival->>'region'), ''),
    category = nullif(pg_catalog.btrim(p_festival->>'category'), ''),
    description = nullif(pg_catalog.btrim(p_festival->>'description'), ''),
    thumbnail_url = nullif(pg_catalog.btrim(p_festival->>'thumbnail_url'), ''),
    official_url = nullif(pg_catalog.btrim(p_festival->>'official_url'), ''),
    price_type = nullif(pg_catalog.btrim(p_festival->>'price_type'), ''),
    price_info = nullif(pg_catalog.btrim(p_festival->>'price_info'), ''),
    program_info = nullif(pg_catalog.btrim(p_festival->>'program_info'), ''),
    status = nullif(pg_catalog.btrim(p_festival->>'status'), ''),
    verification_status = coalesce(
      nullif(pg_catalog.btrim(p_festival->>'verification_status'), ''), 'pending'
    )
  where id = p_festival_id
  returning * into v_after;

  if (pg_catalog.to_jsonb(v_before) - 'updated_at')
     = (pg_catalog.to_jsonb(v_after) - 'updated_at') then
    return v_after.id;
  end if;

  insert into public.audit_events (
    actor_id, actor_name, action_type, festival_id, festival_name
  ) values (
    v_actor_id, v_actor_name, 'festival.updated', v_after.id, v_after.name
  ) returning id into v_event_id;

  insert into public.audit_changes (
    event_id, entity_type, entity_id, entity_label, operation, before_data, after_data
  ) values (
    v_event_id, 'festival', v_after.id::text, v_after.name,
    'update', pg_catalog.to_jsonb(v_before), pg_catalog.to_jsonb(v_after)
  );

  return v_after.id;
end;
$$;

create or replace function public.delete_festival_with_audit(p_festival_id bigint)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor_id uuid := auth.uid();
  v_actor_name text;
  v_before public.festivals%rowtype;
  v_event_id bigint;
begin
  if not public.is_admin() then
    raise exception '관리자 권한이 필요합니다.' using errcode = '42501';
  end if;

  select coalesce(nullif(pg_catalog.btrim(display_name), ''), '관리자')
  into v_actor_name
  from public.profiles
  where id = v_actor_id;

  if v_actor_name is null then
    raise exception '관리자 프로필의 표시 이름을 확인해 주세요.' using errcode = '22023';
  end if;

  select * into v_before
  from public.festivals
  where id = p_festival_id
  for update;

  if not found then
    raise exception '삭제할 축제를 찾을 수 없습니다.' using errcode = 'P0002';
  end if;

  insert into public.audit_events (
    actor_id, actor_name, action_type, festival_id, festival_name
  ) values (
    v_actor_id, v_actor_name, 'festival.deleted', v_before.id, v_before.name
  ) returning id into v_event_id;

  insert into public.audit_changes (
    event_id, entity_type, entity_id, entity_label, operation, before_data, after_data
  ) values (
    v_event_id, 'festival', v_before.id::text, v_before.name,
    'delete', pg_catalog.to_jsonb(v_before), null
  );

  delete from public.festivals where id = p_festival_id;
  return p_festival_id;
end;
$$;

revoke all on function public.create_festival_with_audit(jsonb) from public, anon;
revoke all on function public.update_festival_basic_info_with_audit(bigint, jsonb) from public, anon;
revoke all on function public.delete_festival_with_audit(bigint) from public, anon;

grant execute on function public.create_festival_with_audit(jsonb) to authenticated;
grant execute on function public.update_festival_basic_info_with_audit(bigint, jsonb) to authenticated;
grant execute on function public.delete_festival_with_audit(bigint) to authenticated;

comment on table public.audit_events is '관리자 작업 단위와 작업자 표시 이름 스냅샷';
comment on table public.audit_changes is '감사 이벤트에 포함된 대상별 변경 전후 전체 스냅샷';

commit;
