begin;

create table if not exists public.festival_update_drafts (
  id bigint generated by default as identity primary key,
  festival_id bigint not null references public.festivals(id) on delete cascade,
  source_url text not null,
  source_type text not null default 'instagram_discord',
  draft_json jsonb not null,
  comparison_json jsonb not null default '{}'::jsonb,
  announcement_round text not null default 'unspecified',
  version_number integer not null default 1 check (version_number > 0),
  status text not null default 'pending' check (status in ('pending', 'applied')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  applied_at timestamptz
);

create unique index if not exists festival_update_drafts_source_version_unique
  on public.festival_update_drafts(source_url, version_number);
create index if not exists festival_update_drafts_festival_status_idx
  on public.festival_update_drafts(festival_id, status, created_at desc);

alter table public.festival_update_drafts enable row level security;

drop policy if exists "Admins can read festival update drafts" on public.festival_update_drafts;
create policy "Admins can read festival update drafts"
  on public.festival_update_drafts for select to authenticated
  using (public.is_admin());

drop policy if exists "Admins can update festival update drafts" on public.festival_update_drafts;
create policy "Admins can update festival update drafts"
  on public.festival_update_drafts for update to authenticated
  using (public.is_admin()) with check (public.is_admin());

create or replace function public.create_discord_festival_update_draft(
  p_festival_id bigint,
  p_source_url text,
  p_draft jsonb,
  p_comparison jsonb,
  p_announcement_round text,
  p_regenerate boolean default false
)
returns public.festival_update_drafts
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_festival public.festivals%rowtype;
  v_previous public.festival_update_drafts%rowtype;
  v_created public.festival_update_drafts%rowtype;
  v_version integer := 1;
begin
  if not public.is_festival_bot() then
    raise exception 'Discord Bot 권한이 필요합니다.' using errcode = '42501';
  end if;

  select * into v_festival from public.festivals where id = p_festival_id;
  if not found then
    raise exception '연결할 기존 축제를 찾을 수 없습니다.' using errcode = 'P0002';
  end if;

  if v_festival.normalized_name is distinct from p_draft->'festival'->>'normalized_name'
     or v_festival.start_date is distinct from nullif(p_draft->'festival'->>'start_date', '')::date
     or v_festival.end_date is distinct from nullif(p_draft->'festival'->>'end_date', '')::date then
    raise exception 'JSON과 기존 축제의 식별값이 일치하지 않습니다.' using errcode = '22023';
  end if;

  select * into v_previous
  from public.festival_update_drafts
  where source_url = p_source_url
  order by version_number desc
  limit 1;

  if found and not p_regenerate then
    raise exception 'DUPLICATE_SOURCE_URL' using errcode = '23505';
  end if;
  if found then v_version := v_previous.version_number + 1; end if;

  insert into public.festival_update_drafts (
    festival_id, source_url, draft_json, comparison_json,
    announcement_round, version_number, created_by
  ) values (
    p_festival_id, p_source_url, p_draft, coalesce(p_comparison, '{}'::jsonb),
    coalesce(nullif(p_announcement_round, ''), 'unspecified'), v_version, auth.uid()
  ) returning * into v_created;

  return v_created;
end;
$$;

revoke all on function public.create_discord_festival_update_draft(
  bigint, text, jsonb, jsonb, text, boolean
) from public, anon;
grant execute on function public.create_discord_festival_update_draft(
  bigint, text, jsonb, jsonb, text, boolean
) to authenticated;

comment on table public.festival_update_drafts is
  'Discord-generated JSON drafts linked only to an existing festival update screen.';

commit;
