-- 로그인 사용자의 비공개 페스티벌 관람 기록

begin;

create table if not exists public.user_festival_diaries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  festival_id bigint not null references public.festivals(id) on delete cascade,
  attended_date date not null,
  title text not null,
  content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_festival_diaries_user_festival_unique
    unique (user_id, festival_id),
  constraint user_festival_diaries_title_length
    check (char_length(pg_catalog.btrim(title)) between 1 and 100),
  constraint user_festival_diaries_content_length
    check (char_length(pg_catalog.btrim(content)) between 1 and 10000)
);

create index if not exists user_festival_diaries_user_date_idx
on public.user_festival_diaries (user_id, attended_date desc, id desc);

alter table public.user_festival_diaries enable row level security;

revoke all on table public.user_festival_diaries from anon, authenticated;
grant select, insert, delete on table public.user_festival_diaries to authenticated;
grant update (attended_date, title, content, updated_at)
on table public.user_festival_diaries to authenticated;
grant usage, select on sequence public.user_festival_diaries_id_seq
to authenticated;

drop policy if exists "Users can read own festival diaries"
on public.user_festival_diaries;
create policy "Users can read own festival diaries"
on public.user_festival_diaries
for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can add own festival diaries"
on public.user_festival_diaries;
create policy "Users can add own festival diaries"
on public.user_festival_diaries
for insert to authenticated
with check (
  (select auth.uid()) = user_id
  and exists (
    select 1
    from public.festivals
    where festivals.id = user_festival_diaries.festival_id
      and festivals.verification_status = 'approved'
      and festivals.status in ('ongoing', 'ended')
      and user_festival_diaries.attended_date
        between festivals.start_date and festivals.end_date
  )
);

drop policy if exists "Users can update own festival diaries"
on public.user_festival_diaries;
create policy "Users can update own festival diaries"
on public.user_festival_diaries
for update to authenticated
using ((select auth.uid()) = user_id)
with check (
  (select auth.uid()) = user_id
  and exists (
    select 1
    from public.festivals
    where festivals.id = user_festival_diaries.festival_id
      and festivals.verification_status = 'approved'
      and user_festival_diaries.attended_date
        between festivals.start_date and festivals.end_date
  )
);

drop policy if exists "Users can delete own festival diaries"
on public.user_festival_diaries;
create policy "Users can delete own festival diaries"
on public.user_festival_diaries
for delete to authenticated
using ((select auth.uid()) = user_id);

drop trigger if exists set_user_festival_diaries_updated_at
on public.user_festival_diaries;
create trigger set_user_festival_diaries_updated_at
before update on public.user_festival_diaries
for each row
execute function public.set_updated_at();

comment on table public.user_festival_diaries is
  '로그인 사용자가 본인만 조회하는 페스티벌 관람 기록';

commit;
