-- 개인 페스티벌 아카이브 MVP: 기존 기록 확장 + 실제 관람 공연/곡/외부 미디어 메타데이터

begin;

alter table public.user_festival_diaries
  add column if not exists summary text,
  add column if not exists cover_image_url text,
  add column if not exists favorite_performance_id bigint;

update public.user_festival_diaries
set summary = coalesce(nullif(pg_catalog.btrim(title), ''), left(content, 200))
where summary is null;

alter table public.user_festival_diaries
  add constraint user_festival_diaries_summary_length
  check (summary is null or char_length(pg_catalog.btrim(summary)) between 1 and 200);

create table if not exists public.user_festival_performances (
  id bigint generated by default as identity primary key,
  user_festival_diary_id bigint not null
    references public.user_festival_diaries(id) on delete cascade,
  festival_artist_id bigint not null
    references public.festival_artists(id) on delete cascade,
  rating smallint,
  memo text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_festival_performances_unique
    unique (user_festival_diary_id, festival_artist_id),
  constraint user_festival_performances_rating_range
    check (rating is null or rating between 1 and 5),
  constraint user_festival_performances_memo_length
    check (memo is null or char_length(memo) <= 2000),
  constraint user_festival_performances_id_diary_unique
    unique (id, user_festival_diary_id)
);

alter table public.user_festival_diaries
  add constraint user_festival_diaries_favorite_performance_fkey
  foreign key (favorite_performance_id, id)
  references public.user_festival_performances(id, user_festival_diary_id)
  on delete set null (favorite_performance_id);

create table if not exists public.user_festival_songs (
  id bigint generated by default as identity primary key,
  user_festival_performance_id bigint not null
    references public.user_festival_performances(id) on delete cascade,
  song_name text not null,
  created_at timestamptz not null default now(),
  constraint user_festival_songs_name_length
    check (char_length(pg_catalog.btrim(song_name)) between 1 and 200)
);

create table if not exists public.user_festival_media (
  id bigint generated by default as identity primary key,
  user_festival_performance_id bigint not null
    references public.user_festival_performances(id) on delete cascade,
  provider text not null,
  external_file_id text,
  preview_url text,
  file_type text not null,
  created_at timestamptz not null default now(),
  constraint user_festival_media_provider_length
    check (char_length(pg_catalog.btrim(provider)) between 1 and 50),
  constraint user_festival_media_file_type
    check (file_type in ('image', 'video')),
  constraint user_festival_media_reference_required
    check (external_file_id is not null or preview_url is not null)
);

alter table public.user_festival_performances enable row level security;
alter table public.user_festival_songs enable row level security;
alter table public.user_festival_media enable row level security;

revoke all on public.user_festival_performances,
  public.user_festival_songs,
  public.user_festival_media from anon, authenticated;
grant select, insert, update, delete on public.user_festival_performances,
  public.user_festival_songs,
  public.user_festival_media to authenticated;
grant usage, select on sequence public.user_festival_performances_id_seq,
  public.user_festival_songs_id_seq,
  public.user_festival_media_id_seq to authenticated;
grant update (summary, cover_image_url, favorite_performance_id)
on public.user_festival_diaries to authenticated;

create policy "Users manage own festival performances"
on public.user_festival_performances for all to authenticated
using (exists (
  select 1 from public.user_festival_diaries d
  where d.id = user_festival_diary_id and d.user_id = (select auth.uid())
))
with check (exists (
  select 1 from public.user_festival_diaries d
  join public.festival_artists fa on fa.id = festival_artist_id
  where d.id = user_festival_diary_id
    and d.user_id = (select auth.uid())
    and fa.festival_id = d.festival_id
));

create policy "Users manage own festival songs"
on public.user_festival_songs for all to authenticated
using (exists (
  select 1 from public.user_festival_performances p
  join public.user_festival_diaries d on d.id = p.user_festival_diary_id
  where p.id = user_festival_performance_id and d.user_id = (select auth.uid())
))
with check (exists (
  select 1 from public.user_festival_performances p
  join public.user_festival_diaries d on d.id = p.user_festival_diary_id
  where p.id = user_festival_performance_id and d.user_id = (select auth.uid())
));

create policy "Users manage own festival media"
on public.user_festival_media for all to authenticated
using (exists (
  select 1 from public.user_festival_performances p
  join public.user_festival_diaries d on d.id = p.user_festival_diary_id
  where p.id = user_festival_performance_id and d.user_id = (select auth.uid())
))
with check (exists (
  select 1 from public.user_festival_performances p
  join public.user_festival_diaries d on d.id = p.user_festival_diary_id
  where p.id = user_festival_performance_id and d.user_id = (select auth.uid())
));

create trigger set_user_festival_performances_updated_at
before update on public.user_festival_performances
for each row execute function public.set_updated_at();

create or replace function public.save_user_festival_record(
  p_record_id bigint,
  p_festival_id bigint,
  p_attended_date date,
  p_summary text,
  p_cover_image_url text,
  p_festival_artist_ids bigint[]
)
returns bigint
language plpgsql
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_record_id bigint;
begin
  if v_user_id is null then raise exception '로그인이 필요합니다.'; end if;
  if not exists (
    select 1 from public.festivals f
    where f.id = p_festival_id
      and f.verification_status = 'approved'
      and f.status in ('ongoing', 'ended')
      and p_attended_date between f.start_date and f.end_date
  ) then raise exception '기록할 수 없는 페스티벌 또는 관람일입니다.'; end if;

  if p_record_id is null then
    insert into public.user_festival_diaries (
      user_id, festival_id, attended_date, title, content, summary, cover_image_url
    ) values (
      v_user_id, p_festival_id, p_attended_date,
      left(pg_catalog.btrim(p_summary), 100), pg_catalog.btrim(p_summary),
      pg_catalog.btrim(p_summary), nullif(pg_catalog.btrim(p_cover_image_url), '')
    ) returning id into v_record_id;
  else
    update public.user_festival_diaries
    set attended_date = p_attended_date,
        title = left(pg_catalog.btrim(p_summary), 100),
        content = pg_catalog.btrim(p_summary),
        summary = pg_catalog.btrim(p_summary),
        cover_image_url = nullif(pg_catalog.btrim(p_cover_image_url), '')
    where id = p_record_id and user_id = v_user_id and festival_id = p_festival_id
    returning id into v_record_id;
    if v_record_id is null then raise exception '수정할 기록을 찾을 수 없습니다.'; end if;
  end if;

  delete from public.user_festival_performances
  where user_festival_diary_id = v_record_id;

  insert into public.user_festival_performances (
    user_festival_diary_id, festival_artist_id
  )
  select v_record_id, fa.id
  from public.festival_artists fa
  where fa.festival_id = p_festival_id
    and fa.id = any(coalesce(p_festival_artist_ids, '{}'::bigint[]))
    and coalesce(fa.status, 'confirmed') <> 'cancelled';

  return v_record_id;
end;
$$;

revoke all on function public.save_user_festival_record(
  bigint, bigint, date, text, text, bigint[]
) from public, anon;
grant execute on function public.save_user_festival_record(
  bigint, bigint, date, text, text, bigint[]
) to authenticated;

commit;
